### PR TITLE
Update jquery.js

### PR DESCRIPTION
**Pull request by ChrisAntaki**
Updating to version 2.1.1

### CODE REVIEW

**Comment by vgturtle127** [comment]
@ChrisAntaki Again, I didn't see this opened originally. I'm not sure why. I will update to the latest version manually, but I will merge this first.

**Comment by ChrisAntaki** [comment]
No worries :+1:

**Comment by vgturtle127** [comment]
@ChrisAntaki I see the issue, it has to do with some reversions in my repository. Also, technically the version in your pull request is older than the one in the repo. I will update it manually.

**Comment by vgturtle127** [comment]
@ChrisAntaki Updated manually! :smiley: 

Please test it to make sure everything works smoothly. :smile:

**Pull request closed without merging**
